ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "25.1.0"
    hooks:
      - id: black-jupyter

  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.*]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=100"]
        verbose: true

  # Code linting (after formatting)
  #- repo: https://github.com/pycqa/flake8
  #  rev: 6.0.0
  #  hooks:
  #    - id: flake8
  #      args: [--max-line-length=100, --extend-ignore=E203,W503]
  #      verbose: true
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.4"
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: ["--fix", "--show-fixes"]
        exclude: ^data/rucio_utils.py|^src/HH4b/corrections/(data|makePUReWeightJSON.py)
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.4.1"
    hooks:
      - id: codespell
        types_or: [python, rst, markdown]
        args: ["--ignore-words", ".codespell-whitelist.txt"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck
        exclude: .*templ.sh

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.32.1
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs
