model_name: "trained_DeepMET"  # Choose from available models

# not implemented yet 

# HLS config parameters
config_params:
  reuse-factor: 1
  strategy: "Latency"
  precision: "ap_fixed<32,16>"
  trace: true


io_type: "io_parallel"
part: "xcvu13p-flga2577-2-e"
clock_period: 5
project_name: "L1METML_v1"
batch_size: 1
synth: false
normFac: 1  # Identify where NormFac is used and if it can be fed via argument
