apiVersion: v1
kind: Pod
metadata:
  name: l1metml-pod1
spec:
  containers:
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/jmduarte/l1metml:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: 12Gi
        cpu: "2"
        nvidia.com/gpu: "1"
      requests:
        memory: 12Gi
        cpu: "1"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /l1metmlvol
      name: l1metmlvol
  restartPolicy: Never
  volumes:
    - name: l1metmlvol
      persistentVolumeClaim:
        claimName: l1metmlvol
